name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            8.0.x
            9.0.x
            10.0.x

      - name: Restore
        run: dotnet restore src/OptiPowerTools.Hangfire/OptiPowerTools.Hangfire.csproj

      - name: Restore Tools Tests
        run: dotnet restore tests/OptiPowerTools.Hangfire.Tools.Tests/OptiPowerTools.Hangfire.Tools.Tests.csproj

      - name: Build
        run: dotnet build src/OptiPowerTools.Hangfire/OptiPowerTools.Hangfire.csproj --no-restore -c Release

      - name: Build Tools
        run: dotnet build src/OptiPowerTools.Hangfire.Tools/OptiPowerTools.Hangfire.Tools.csproj --no-restore -c Release

      - name: Test
        run: dotnet test tests/OptiPowerTools.Hangfire.Tests/OptiPowerTools.Hangfire.Tests.csproj -c Release --collect:"XPlat Code Coverage"

      - name: Test Tools
        run: dotnet test tests/OptiPowerTools.Hangfire.Tools.Tests/OptiPowerTools.Hangfire.Tools.Tests.csproj -c Release --collect:"XPlat Code Coverage"

      - name: Pack
        run: dotnet pack src/OptiPowerTools.Hangfire/OptiPowerTools.Hangfire.csproj --no-build -c Release
